#! /bin/bash
#
#	mcpasswd - Minecraft user management wrapper
#
#	Version 2.1.0
#
#	Copyright (C) 2012 Richard Neumann <mail@richard-neumann.de>
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.

# XXX: Note that 'mcpasswd' is only a wrapper.
# The orderly way to manage users on the servers is using
# minectl <server_name> passwd [COMMANDS]

# First argument is the server name
SERVER_NAME=$1
shift

# Redirect to minectl
echo "WARNING: `basename $0` is deprecated and will be removed in future versions of minectl.
Use
	minectl <server_name> passwd [COMMANDS]
to perform operations regarding the user management in the future.

Redirecting to '`dirname $0`/minectl "$SERVER_NAME" passwd'"
`dirname $0`/minectl "$SERVER_NAME" passwd $@
